import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  const [count, setCount] = useState("—");
  const getCount = () => {
    axios
      .get("/api/count")
      .then(function (response) {
        // handle success
        console.log(response);
        setCount(response.data.count);
      })
      .catch(function (error) {
        // handle error
        console.log(error);
      })
      .then(function () {
        // always executed
      });
  };
  const upTick = () => {
    axios
      .post("/api/count")
      .then(function (response) {
        // handle success
        console.log(response);
        setCount(response.data.count);
      })
      .catch(function (error) {
        // handle error
        console.log(error);
      })
      .then(function () {
        // always executed
      });
  };
  useEffect(() => {
    getCount();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>The count is {count}</h1>

        <p className={styles.description}>
          <button
            style={{
              padding: 16,
              letterSpacing: "0.04em",
              height: 120,
              width: 120,
              border: 0,
              cursor: "pointer",
              color: "white",
              borderRadius: 60,
              backgroundColor: "darkslategray",
              fontSize: 40,
              fontWeight: 800,
            }}
            onClick={upTick}
          >
            +1
          </button>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
